name: Print Run Info
description: 'This action prints the GitHub context information'
runs:
  using: "composite"
  steps:
    - name: Print github Context
      shell: bash
      run: |
        echo """
          Ref: ${{ github.ref }}
          SHA: ${{ github.sha }}
          Run Number: ${{ github.run_number }}
          Head Ref: ${{ github.head_ref }}
          Base Ref: ${{ github.base_ref }}
          Event Name: ${{ github.event_name }}
        """
