name: SonarQube Scan
description: 'This action runs a SonarQube scan on the specified project directory'
inputs:
  token:
    description: 'The SonarQube token'
    required: true
  project-dir:
    description: 'The scope where SonarQube should be run'
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Scan
      uses: SonarSource/sonarqube-scan-action@bfd4e558cda28cda6b5defafb9232d191be8c203 #v4.2.1
      env:
        SONAR_TOKEN: ${{ inputs.token }}
        GOPATH: ${{ inputs.project-dir }}
      with:
        projectBaseDir: ${{ inputs.project-dir }}
