name: Docker Build/Push
inputs:
  service:
    description: 'The service name in src/'
    required: true
  registry-username:
    description: 'The username for the registry to push to'
    required: true
  registry-password:
    description: 'The password for the registry to push to'
    required: true
  push:
    description: 'Push the image to registry or not'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
    - name: Docker extract metadata
      id: meta
      if: ${{ inputs.push == 'true' }}
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}/${{ inputs.service }}
    - name: Log in to GitHub Packages
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: Docker Build & Push
      id: build-push
      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 #v6.10.0
      with:
        file: "src/${{ inputs.service }}/build/Dockerfile"
        context: "src/${{ inputs.service }}"
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ inputs.push == 'true' }}
    - name: Generate artifact attestation
      if: ${{ inputs.push == 'true' }}
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}/${{ inputs.service }}
        subject-digest: ${{ steps.build-push.outputs.digest }}
        push-to-registry: true
