name: "Cleanup Old Github Packages"
on:
  schedule:
    - cron: "15 16 * * *"
jobs:
  clean-docker:
    name: Clean Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ ledgersvc ]
    steps:
      - name: Delete images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.repository }}/${{ matrix.project }}
          package-type: container
          min-versions-to-keep: 25
