name: SonarQube
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  scan-base:
    name: scan-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BASE }}
        with:
          args:
            -Dsonar.projectKey=fursave_base
            -Dsonar.organization=kneadcode
            -Dsonar.exclusions=src/**/*
  scan-golib:
    name: scan-golib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GOLIB }}
        with:
          projectBaseDir: src/golib/
          args:
            -Dsonar.projectKey=fursave_golib
            -Dsonar.organization=kneadcode
            -Dsonar.cpd.exclusions=**/*_test.go
  scan-ledgersvc:
    name: scan-ledgersvc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_LEDGERSVC }}
        with:
          projectBaseDir: src/ledgersvc/
          args:
            -Dsonar.projectKey=fursave_ledgersvc
            -Dsonar.organization=kneadcode
            -Dsonar.cpd.exclusions=**/*_test.go
